eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
    healthcheck:
      enabled: true # 开启监控检查（需要spring-boot-starter-actuator依赖）
  instance:
    lease-renewal-interval-in-seconds: 30 # 租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 60 #租期到期时间（默认90秒）
server:
  port: 2224
spring:
  application:
    name: sc-eureka-consumer-feign
#feign的配置，连接超时及读取超时配置
feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: basic
