server:
    port: 1111 #服务注册中心端口号
eureka:
    instance:
        hostname: 127.0.0.1 #服务注册中心IP地址
        lease-renewal-interval-in-seconds: 30 # 租期更新时间间隔（默认30秒）
        lease-expiration-duration-in-seconds: 60 #租期到期时间（默认90秒）
    client:
        registerWithEureka: false #是否向服务注册中心注册自己
        fetchRegistry: false #是否检索服务
        serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        healthcheck:
            enabled: true # 开启监控检查
    server:
        enable-self-preservation: false # 自我保护设置
        eviction-interval-timer-in-ms: 0 #清理失效服务时间间隔（0立即清除）
spring:
    application:
        name: sc-eureka-server