#设置服务端主机地址
eureka:
    #设置服务注册中心的URL
    client:
        serviceUrl:
            defaultZone: http://10.16.168.16:1111/eureka
        #注册中心不需要注册自己
        register-with-eureka: false
        #注册中心不需要去发现服务
        fetch-registry: false
#设置tomcat服务端口号
server:
    port: 2222
#设置服务名称
spring:
    application:
        name: eureka-service-client


