server:
    port: 8090
spring:
    profiles:
        active: 
    activiti:
        # 自动建表
        database-schema: ACTIVITI
        database-schema-update: true
        history-level: full
        db-history-used: true
    # 数据源配置
    datasource:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
        username: root
        password: 123456
        initsize: 10
        maxActive: 20
        minIdle: 10
        maxWait: 120000
        poolPreparedStatements: false
        maxOpenPreparedStatements: -1
        validationQuery: select 1
        testOnborrow: true
        testOnReturn: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 120000
        filters: log4j,stat
    # 模板引擎
    freemarker:
        #内容格式
        content-type: text/html
        #缓存配置
        cache: false
        #模板路径
        template-loader-path: classpath:/templates
        #编码格式
        charset: UTF-8
        #是否启用
        enabled: true
        #请求内容属性
        request-context-attribute: request
        expose-request-attributes: true
        expose-session-attributes: true
        #检查模板路径
        check-template-location: true
        #文件后缀
        suffix: .ftl